Upload file
kh-026-webui-python/backend pull request #13
Opened 2019-04-02 09:48 UTC by MarynaSirenko

Endpoint for the files

2019-04-02 11:23 UTC, HolmesInc requested changes

2019-04-02 11:23 UTC, HolmesInc commented on backend/api/admin.py
>  from django.contrib.auth.models import User
Удали эту строчку вообще

2019-04-02 11:23 UTC, HolmesInc commented on backend/api/serializers.py
> +import os
Это то же тут не нужно

2019-04-02 11:23 UTC, HolmesInc commented on backend/api/models.py
> +class HealthCheck(models.Model):
Этот класс то же удали

2019-04-02 11:23 UTC, HolmesInc commented on backend/backend/settings.py
> +          'rollbar': {
А зачем ты это разкомментила?

2019-04-02 11:23 UTC, HolmesInc commented on backend/backend/settings.py
> +REST_FRAMEWORK = {
Я бы предпочел что бы эксепшены пока только в консоль сыпались

2019-04-03 09:39 UTC, ruzniaievdm approved these changes

2019-04-03 17:33 UTC, merged